[package]

name = "hermann"
version = "0.0.1"
authors = ["Andrew Oppenlander <andrew.oppenlander@gmail.com>"]

[dependencies]

docopt = "*"
rustc-serialize = "*"

[dependencies.image]

git = "https://github.com/PistonDevelopers/image"
